### ISSUE TITLE
add kube support ... add manifest

### ISSUE THREAD

**Issue by RichardHightower** [cloudurable/kube-training#9]
```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
  - port: 8080
    name: hello-world
  selector:
    app: hello-world
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: cloudurable/hello-kube:0.0.1
        name: hello-world
        ports:
        - containerPort: 8080
          name: hello-world
        command: ["java", "-jar", "/app.jar"] 

```
